# JVM
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# Signing
RELEASE_STORE_FILE=C:/Users/pe603380/release-keystore.jks
RELEASE_STORE_PASSWORD=memotripkroniq
RELEASE_KEY_ALIAS=memotrip_release
RELEASE_KEY_PASSWORD=memotripkroniq
